server:
  port: 8080
  
spring:

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
        - id: authentication-service
          uri: http://localhost:8095
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
        - id: email-service
          uri: http://localhost:8075
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}
        - id: tag-service
          uri: http://localhost:8070
          predicates:
            - Path=/tag-service/**
          filters:
            - RewritePath=/tag-service(?<segment>/?.*), $\{segment}
        - id: interviewer-service
          uri: http://localhost:8097
          predicates:
            - Path=/interviewer-service/**
          filters:
            - RewritePath=/interviewer-service(?<segment>/?.*), $\{segment}
        - id: interviewee-service
          uri: http://localhost:8098
          predicates:
            - Path=/interviewee-service/**
          filters:
            - RewritePath=/interviewee-service(?<segment>/?.*), $\{segment}

